version: '3.8'


networks:
  inception:
    driver: "bridge"


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dmaessen/data/db # is this an issue??
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dmaessen/data/wp # is this an issue??
      o: bind


services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - /home/dmaessen/data/db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
    volumes:
      - /home/dmaessen/data/wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
    ports:
      - 443:443
    volumes:
      - /home/dmaessen/data/wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
